### ISSUE TITLE
sod_comb.sh issue after updating to MacOS 12

### ISSUE THREAD

**Issue by uthpalaherath** [gcmt-group/sod#1]
Dear developer, 

I've been using sod for a while now without any issue. Today, I updated to MacOS 12 and I get the following error when running sod_comb.sh:

`/Users/uthpala/sod/bin/sod_comb.sh: line 14: [: -ne: unary operator expected`

It seems to be coming from bash and I surrounded the variables in sod_comb.sh with "" but it resulted in other errors. I was just wondering if anyone else who updates their OS has been seeing the same issues. 

Thank you, 

Best,
Uthpala

**Comment by uthpalaherath** [comment]
UPDATE:

This issue seems to be coming from the gfortran compiler supplied with MacOS 12. When I used Intel fortran compliers there was no issue. 

-Uthpala

**Comment by rgraucrespo** [comment]
Thank you Uthpala. No idea why that gfortran compiler is giving that problem.

**Comment by uthpalaherath** [comment]
You're welcome. Hopefully, they get it working with an update with Xcode for Mac.
